CREATE TABLE TB_CAR
(
    CAR_PLATE CHAR(7),
    CAR_NAME VARCHAR(20),
    CAR_COLOR VARCHAR(20),
    MODEL_YEAR INT,
    FABRICATION_YEAR INT
    CONSTRAINT PK_CAR PRIMARY KEY(CAR_PLATE)
)

CREATE TABLE TB_SERVICE
(
    ID INT IDENTITY(1,1),
    DESCRIPTION_SERVICE VARCHAR(50),
    CONSTRAINT PK_SERVICE PRIMARY KEY(ID)
)

CREATE TABLE TB_CAR_SERVICE
(
    ID INT IDENTITY(1,1),
    CAR_ID CHAR(7),
    SERVICE_ID INT,
    STATUS_SERVICE BIT
    CONSTRAINT PK_CAR_SERVICE PRIMARY KEY(ID)
    CONSTRAINT FK_CAR FOREIGN KEY(CAR_ID) REFERENCES TB_CAR(CAR_PLATE),
    CONSTRAINT FK_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES TB_SERVICE(ID)
)

SELECT * FROM TB_CAR;
SELECT * FROM TB_SERVICE;
SELECT * FROM TB_CAR_SERVICE;

DROP TABLE TB_CAR;

TRUNCATE TABLE TB_CAR
TRUNCATE TABLE TB_CAR_SERVICE

--SELECT PARA TRAZER OS CARROS SERVICOS EM ANDAMENTO
SELECT C.CAR_PLATE, C.CAR_NAME, C.CAR_COLOR, C.MODEL_YEAR, C.FABRICATION_YEAR
FROM TB_CAR_SERVICE CC
JOIN TB_CAR C ON CC.CAR_ID = C.CAR_PLATE AND CC.STATUS_SERVICE = 1
ORDER BY C.FABRICATION_YEAR DESC;

--SELECT PARA TRAZER OS CARROS VERMELHOS
SELECT CAR_PLATE, CAR_NAME, CAR_COLOR, MODEL_YEAR, FABRICATION_YEAR
FROM TB_CAR
WHERE CAR_COLOR = 'Vermelho'

--SELECT PARA TRAZER OS CARROS FABRICADOS ENTRE 2010 E 2011
SELECT CAR_PLATE, CAR_NAME, CAR_COLOR, MODEL_YEAR, FABRICATION_YEAR
FROM TB_CAR
WHERE FABRICATION_YEAR = 2010 OR FABRICATION_YEAR = 2011